### ISSUE TITLE
Crash on startup when using Quilt on 1.19.2

### ISSUE THREAD

**Issue by netcore10** [Klotzi111/amecs#1]
note: Quilt uses the same fabric mappings, but there could be a problem there too, but 99.9% of mods i've tried haven't broken on quilt yet.

https://paste.atlauncher.com/view/934f2db6-7f18-4ce4-bc10-7dc09f6892e6

**Comment by Klotzi111** [comment]
Weird. It seems like that the mod `fabricloader` is not installed in your modpack. But it is the main component of fabric that loads all other mods. Do you know what kind of mod loader you have? Since you seemingly do not have `fabricloader`.

**Comment by Klotzi111** [comment]
I see. It is mentioned in the logs: The loader is `Quilt 0.17.5-beta.1`. I have never seen it. I will look into it. And how I can fix the problem.

**Comment by netcore10** [comment]
> I see. It is mentioned in the logs: The loader is `Quilt 0.17.5-beta.1`. I have never seen it. I will look into it. And how I can fix the problem.

It's essentially a community based enhanced fabric, but they kept the fabric mappings and api for the forseeable future. Fabric api is there, it's just either, not noticed because of the way they do it, or named differently.

**Comment by netcore10** [comment]
> > I see. It is mentioned in the logs: The loader is `Quilt 0.17.5-beta.1`. I have never seen it. I will look into it. And how I can fix the problem.
> 
> It's essentially a community based enhanced fabric, but they kept the fabric mappings and api for the forseeable future. Fabric api is there, it's just either, not noticed because of the way they do it, or named differently.

They use "Quilt standar libraries/Quilted Fabric API"

**Comment by Klotzi111** [comment]
Okay. I think I fixed it. My fork of amecs uses my helper library [FabricMultiVersionHelper](https://github.com/Klotzi111/FabricMultiVersionHelper/releases/). If you download the latest release and add it to your `mods` folder, it should work. Because the loader will prefer the newer version of `FabricMultiVersionHelper` and this newer version is fixed. Please try it.

**Comment by netcore10** [comment]
Bingo! thanks a lot! <3

**Comment by netcore10** [comment]
This crashes on quilts latest beta update, for some reason.

**Comment by Klotzi111** [comment]
@netcore10 I guess that reopen was accidental

**Comment by netcore10** [comment]
yeah apologies!
